/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Beans.BeansPacientes;
import Beans.ModeloTabela;
import Conex.ConexaoBD;
import Dao.DaoPaciente;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Notorius B.I.G
 */
public class FormPaciente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    BeansPacientes pac = new BeansPacientes();
    DaoPaciente dao = new DaoPaciente();
    int flag = 0;
    int resposta = 0;

    public FormPaciente() {
        initComponents();
        preencherBairros();
        preencheTabela("select paci_codigo,paci_nome,paci_telefone,paci_rg,badnome from pacientes inner join bairro on paci_baicodigo = badcodigo order by paci_nome");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNasc = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodPac = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome :");

        jTextFieldNome.setEnabled(false);

        jLabel2.setText("Nascimento : ");

        jLabel3.setText("Rg :");

        jLabel4.setText("Telefone :");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldRua.setEnabled(false);

        jLabel6.setText("Rua :");

        jLabel7.setText("Complemento :");

        jTextFieldComplemento.setEnabled(false);

        jLabel8.setText("Cep:");

        jLabel9.setText("Bairro : ");

        jComboBoxBairro.setEnabled(false);

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComplemento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jLabel5.setText("Pesquisar : ");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRg.setEnabled(false);

        try {
            jFormattedTextFieldFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFone.setEnabled(false);

        try {
            jFormattedTextFieldNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNasc.setEnabled(false);

        jLabel10.setText("ID :");

        jTextFieldCodPac.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldFone))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(1, 1, 1))
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addGap(23, 23, 23))
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Formulario de Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel11)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(755, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o nome para continuar");
            jTextFieldNome.requestFocus();
        } else if (jFormattedTextFieldNasc.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "preencha a Data Nascimento  para Continuar ");
            jFormattedTextFieldNasc.requestFocus();
        } else if (jFormattedTextFieldRg.getText().equals("       - ")) {
            JOptionPane.showMessageDialog(null, "preencha O RG  para Continuar ");
            jFormattedTextFieldRg.requestFocus();
        } else if (jFormattedTextFieldFone.equals("     -    ")) {
            JOptionPane.showMessageDialog(null, "preencha a Telefone  para Continuar ");
            jFormattedTextFieldFone.requestFocus();
        } else if (jTextFieldRua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha a Rua  para Continuar ");
            jTextFieldRua.requestFocus();
        } else if (jFormattedTextFieldCep.getText().equals("  .   -   ")) {
            JOptionPane.showMessageDialog(null, "preencha a Cep  para Continuar ");
            jFormattedTextFieldCep.requestFocus();
        } else if (jTextFieldComplemento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha a Data Nascimento  para Continuar ");
            jTextFieldComplemento.requestFocus();
        } else {
            if (flag == 1) {
                pac.setNomePac(jTextFieldNome.getText());
                pac.setCep(jFormattedTextFieldCep.getText());
                pac.setComplemento(jTextFieldComplemento.getText());
                pac.setNasc(jFormattedTextFieldNasc.getText());
                pac.setRg(jFormattedTextFieldRg.getText());
                pac.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
                pac.setTelefone(jFormattedTextFieldFone.getText());
                pac.setRua(jTextFieldRua.getText());
                dao.Salvar(pac);
                preencheTabela("select paci_codigo,paci_nome,paci_telefone,paci_rg,badnome from pacientes inner join bairro on paci_baicodigo = badcodigo order by paci_nome");

                jTextFieldNome.setEnabled(!true);
                jTextFieldCodPac.setEnabled(!true);
                jFormattedTextFieldNasc.setEnabled(!true);
                jFormattedTextFieldRg.setEnabled(!true);
                jFormattedTextFieldFone.setEnabled(!true);
                jTextFieldRua.setEnabled(!true);
                jFormattedTextFieldCep.setEnabled(!true);
                jTextFieldComplemento.setEnabled(!true);
                jComboBoxBairro.setEnabled(!true);

                jButtonCancelar.setEnabled(!true);
                jButtonSalvar.setEnabled(!true);
                jButtonNovo.setEnabled(!false);
                jButtonAlterar.setEnabled(false);
                jButtonExcluir.setEnabled(false);

                //LimparCampo
                jTextFieldCodPac.setText("");
                jTextFieldComplemento.setText("");
                jTextFieldNome.setText("");
                jTextFieldRua.setText("");
                jFormattedTextFieldCep.setText("");
                jFormattedTextFieldNasc.setText("");
                jFormattedTextFieldRg.setText("");
                jFormattedTextFieldFone.setText("");

            } else {
                pac.setNomePac(jTextFieldNome.getText());
                pac.setCep(jFormattedTextFieldCep.getText());
                pac.setComplemento(jTextFieldComplemento.getText());
                pac.setNasc(jFormattedTextFieldNasc.getText());
                pac.setRg(jFormattedTextFieldRg.getText());
                pac.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
                pac.setTelefone(jFormattedTextFieldFone.getText());
                pac.setRua(jTextFieldRua.getText());
                pac.setCodPac(Integer.parseInt(jTextFieldCodPac.getText()));
                dao.Alterar(pac);
                preencheTabela("select paci_codigo,paci_nome,paci_telefone,paci_rg,badnome from pacientes inner join bairro on paci_baicodigo = badcodigo order by paci_nome");

                jTextFieldNome.setEnabled(!true);
                jTextFieldCodPac.setEnabled(!true);
                jFormattedTextFieldNasc.setEnabled(!true);
                jFormattedTextFieldRg.setEnabled(!true);
                jFormattedTextFieldFone.setEnabled(!true);
                jTextFieldRua.setEnabled(!true);
                jFormattedTextFieldCep.setEnabled(!true);
                jTextFieldComplemento.setEnabled(!true);
                jComboBoxBairro.setEnabled(!true);

                jButtonCancelar.setEnabled(!true);
                jButtonSalvar.setEnabled(!true);
                jButtonNovo.setEnabled(!false);
                jButtonAlterar.setEnabled(false);
                jButtonExcluir.setEnabled(false);

                //LimparCampo
                jTextFieldCodPac.setText("");
                jTextFieldComplemento.setText("");
                jTextFieldNome.setText("");
                jTextFieldRua.setText("");
                jFormattedTextFieldCep.setText("");
                jFormattedTextFieldNasc.setText("");
                jFormattedTextFieldRg.setText("");
                jFormattedTextFieldFone.setText("");

            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldCodPac.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldFone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jComboBoxBairro.setEnabled(true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldCodPac.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldFone.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jComboBoxBairro.setEnabled(true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jTextFieldCodPac.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRg.setEnabled(!true);
        jFormattedTextFieldFone.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFieldCep.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);

        pac.setPequisas(jTextFieldPesquisa.getText());
        BeansPacientes pac1 = dao.buscaPaciente(pac);
        jTextFieldNome.setText(pac1.getNomePac());
        jTextFieldCodPac.setText(String.valueOf(pac1.getCodPac()));
        jFormattedTextFieldNasc.setText(pac1.getNasc());
        jFormattedTextFieldRg.setText(pac1.getRg());
        jFormattedTextFieldFone.setText(pac1.getTelefone());
        jTextFieldRua.setText(pac1.getRua());
        jFormattedTextFieldCep.setText(pac1.getCep());
        jTextFieldComplemento.setText(pac1.getComplemento());
        jComboBoxBairro.setSelectedItem(pac1.getNomeBairro());


    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Excluir");
        if (resposta == JOptionPane.YES_OPTION) {
            pac.setCodPac(Integer.parseInt(jTextFieldCodPac.getText()));
            dao.Excluir(pac);
            preencheTabela("select paci_codigo,paci_nome,paci_telefone,paci_rg,badnome from pacientes inner join bairro on paci_baicodigo = badcodigo order by paci_nome");

            jTextFieldCodPac.setText("");
            jTextFieldComplemento.setText("");
            jTextFieldNome.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldNasc.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldFone.setText("");

            jTextFieldNome.setEnabled(!true);
            jTextFieldCodPac.setEnabled(!true);
            jFormattedTextFieldNasc.setEnabled(!true);
            jFormattedTextFieldRg.setEnabled(!true);
            jFormattedTextFieldFone.setEnabled(!true);
            jTextFieldRua.setEnabled(!true);
            jFormattedTextFieldCep.setEnabled(!true);
            jTextFieldComplemento.setEnabled(!true);
            jComboBoxBairro.setEnabled(!true);

            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonAlterar.setEnabled(!false);
            jButtonExcluir.setEnabled(!false);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        String nome_paciente = "" + jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 1);
        conex.conexao();
        try {
            conex.executaSql("select *from pacientes where paci_nome='" + nome_paciente + "'");
            conex.rs.first();
            jTextFieldCodPac.setText(String.valueOf(conex.rs.getInt("paci_codigo")));
            jTextFieldNome.setText(conex.rs.getString("paci_nome"));
            jFormattedTextFieldNasc.setText(conex.rs.getString("paci_nasc"));
            jFormattedTextFieldRg.setText(conex.rs.getString("paci_rg"));
            jFormattedTextFieldFone.setText(conex.rs.getString("paci_telefone"));
            jTextFieldRua.setText(conex.rs.getString("paci_rua"));
            jTextFieldComplemento.setText(conex.rs.getString("paci_complemento"));
            jFormattedTextFieldCep.setText(conex.rs.getString("paci_cep"));

            ConexaoBD conexPesquisa = new ConexaoBD();
            conexPesquisa.conexao();
            conexPesquisa.executaSql("select *from bairro where badcodigo =" + conex.rs.getInt("paci_baicodigo"));
            conexPesquisa.rs.first();
            jComboBoxBairro.setSelectedItem(conexPesquisa.rs.getString("badnome"));
            conexPesquisa.desconecta();
            
            //quando Clicar Libera os capos e Desbloqueia 
            jTextFieldNome.setEnabled(!true);
            jTextFieldCodPac.setEnabled(!true);
            jFormattedTextFieldNasc.setEnabled(!true);
            jFormattedTextFieldRg.setEnabled(!true);
            jFormattedTextFieldFone.setEnabled(!true);
            jTextFieldRua.setEnabled(!true);
            jFormattedTextFieldCep.setEnabled(!true);
            jTextFieldComplemento.setEnabled(!true);
            jComboBoxBairro.setEnabled(!true);

            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonAlterar.setEnabled(!false);
            jButtonExcluir.setEnabled(!false);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar dados " + e.getMessage());
        }
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldCodPac.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldCep.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldFone.setText("");

        jTextFieldNome.setEnabled(!true);
        jTextFieldCodPac.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRg.setEnabled(!true);
        jFormattedTextFieldFone.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFieldCep.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);

        jButtonCancelar.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public void preencherBairros() {
        conex.conexao();
        conex.executaSql("select *from bairro order by badnome");
        try {
            conex.rs.first();
            jComboBoxBairro.removeAllItems();
            do {
                jComboBoxBairro.addItem(conex.rs.getString("badnome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher bairros" + ex);

        }
        conex.desconecta();
    }

    public void preencheTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "Telefone", "Rg", "Bairro"};
        conex.conexao();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("paci_codigo"), conex.rs.getString("paci_nome"), conex.rs.getString("paci_telefone"), conex.rs.getString("paci_rg"), conex.rs.getString("badnome")});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque por outro Paciente para Preencher a Tabela " + ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTablePacientes.setModel(modelo);
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(30);//coluna e largura da Col = 23
        jTablePacientes.getColumnModel().getColumn(0).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(220);//coluna e largura da Col = 23
        jTablePacientes.getColumnModel().getColumn(1).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(80);//coluna e largura da Col = 23
        jTablePacientes.getColumnModel().getColumn(2).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(120);//coluna e largura da Col = 23
        jTablePacientes.getColumnModel().getColumn(3).setResizable(false);
        jTablePacientes.getTableHeader().setReorderingAllowed(false);
        jTablePacientes.setAutoResizeMode(jTablePacientes.AUTO_RESIZE_OFF);
        jTablePacientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxBairro;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldFone;
    private javax.swing.JFormattedTextField jFormattedTextFieldNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldCodPac;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
