/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conex.ConexaoBD;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Notorius B.I.G
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    FormMedico tela = new FormMedico();
    FormUsuario telaUsu = new FormUsuario();
    FormPaciente telaPaci = new FormPaciente();
    FormAgendamento telaAgen = new FormAgendamento();

    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipal() {
        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jInternalFrameSejaBemVindo = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonMedico = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonEnfermeiras = new javax.swing.JButton();
        jButtonPacientes = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItemEnfermeiras = new javax.swing.JMenuItem();
        jMenuItemPacientes = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jInternalFrameSejaBemVindo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrameSejaBemVindo.setClosable(true);
        jInternalFrameSejaBemVindo.setIconifiable(true);
        jInternalFrameSejaBemVindo.setMaximizable(true);
        jInternalFrameSejaBemVindo.setTitle("Bem Vindo");
        jInternalFrameSejaBemVindo.setToolTipText("");
        jInternalFrameSejaBemVindo.setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Cadastros : ");

        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png/CadMedicos.png"))); // NOI18N
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });

        jLabel4.setText("Agendas :");

        jButtonEnfermeiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png/icon-infermeira.png"))); // NOI18N

        jButtonPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png/cadPacientes.png"))); // NOI18N
        jButtonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacientesActionPerformed(evt);
            }
        });

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Png/Agenda.png"))); // NOI18N
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnfermeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButtonEnfermeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Sistema de Gerenciamento : ");

        javax.swing.GroupLayout jInternalFrameSejaBemVindoLayout = new javax.swing.GroupLayout(jInternalFrameSejaBemVindo.getContentPane());
        jInternalFrameSejaBemVindo.getContentPane().setLayout(jInternalFrameSejaBemVindoLayout);
        jInternalFrameSejaBemVindoLayout.setHorizontalGroup(
            jInternalFrameSejaBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameSejaBemVindoLayout.createSequentialGroup()
                .addGroup(jInternalFrameSejaBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameSejaBemVindoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jInternalFrameSejaBemVindoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jInternalFrameSejaBemVindoLayout.setVerticalGroup(
            jInternalFrameSejaBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameSejaBemVindoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Clinica Sao Jose ");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Usuairos : ");

        jLabelUsuario.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 255));
        jLabelUsuario.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInternalFrameSejaBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(250, 250, 250)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jInternalFrameSejaBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastro");

        jMenuItemMedico.setText("Médicos");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMedico);

        jMenuItemEnfermeiras.setText("Enfermerias");
        jMenu1.add(jMenuItemEnfermeiras);

        jMenuItemPacientes.setText("Pacientes");
        jMenuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPacientes);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relátorio");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Agenda");

        jMenuItem2.setText("Agenda Hoje");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem1.setText("Agenda Medico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Sair");

        jMenuItem5.setText("Sair");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(982, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
        try {
            conecta.executaSql("select *from usuarios where usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("administrador")) {
                //para q as janela Form Medicos nao abra varias de uma vez 
                if (tela == null) {
                    tela = new FormMedico();
                    tela.setVisible(true);
                    tela.setResizable(false);
                } else {
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");

        }
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        jInternalFrameSejaBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        try {
            conecta.executaSql("select *from usuarios where usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("administrador")) {
                //para q as janela Form Medicos nao abra varias de uma vez 
                if (telaUsu == null) {
                    telaUsu = new FormUsuario();
                    telaUsu.setVisible(true);
                    telaUsu.setResizable(false);
                } else {
                    telaUsu.setVisible(true);
                    telaUsu.setResizable(false);
                }
                //FormUsuario tela = new FormUsuario();
                //tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");

        }
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
        //Permitido para Usuario Administrador
        try {
            conecta.executaSql("select *from usuarios where usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("administrador")) {
                //para q as janela Form Medicos nao abra varias de uma vez 
                if (tela == null) {
                    tela = new FormMedico();
                    tela.setVisible(true);
                    tela.setResizable(false);
                } else {
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");

        }
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jButtonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacientesActionPerformed
        //Permitido para Usuario Administrador
        try {
            conecta.executaSql("select *from usuarios where usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("administrador")) {
                //para q as janela Form Medicos nao abra varias de uma vez 
                if (telaPaci == null) {
                    telaPaci = new FormPaciente();
                    telaPaci.setVisible(true);
                    telaPaci.setResizable(false);
                } else {
                    telaPaci.setVisible(true);
                    telaPaci.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");

        }
    }//GEN-LAST:event_jButtonPacientesActionPerformed

    private void jMenuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacientesActionPerformed
        //Permitido para Usuario Administrador
        try {
            conecta.executaSql("select *from usuarios where usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("administrador")) {
                //para q as janela Form Medicos nao abra varias de uma vez 
                if (telaPaci == null) {
                    telaPaci = new FormPaciente();
                    telaPaci.setVisible(true);
                    telaPaci.setResizable(false);
                } else {
                    telaPaci.setVisible(true);
                    telaPaci.setResizable(false);
                }
                //FormMedico tela = new FormMedico();
                //tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");

        }
    }//GEN-LAST:event_jMenuItemPacientesActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        try {
            conecta.executaSql("select *from usuarios where usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("administrador")) {
                //para q as janela Form Medicos nao abra varias de uma vez 
                if (telaAgen == null) {
                    telaAgen = new FormAgendamento();
                    telaAgen.setVisible(true);
                    telaAgen.setResizable(false);
                } else {
                    telaAgen.setVisible(true);
                    telaAgen.setResizable(false);
                }
                //FormUsuario tela = new FormUsuario();
                //tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "voce nao tem permisao para essa funcionalidade");

        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormAgendaMedico tela = new FormAgendaMedico();
        tela.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormAgenda tela = new FormAgenda();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonEnfermeiras;
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonPacientes;
    private javax.swing.JInternalFrame jInternalFrameSejaBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemEnfermeiras;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemPacientes;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
